CREATE DATABASE Nota_Fiscal
USE Nota_Fiscal

DROP TABLE IF EXISTS Nota_Fiscal;

CREATE TABLE tbcabecalho
(IDNF INT,
DATA_EMISSAO DATE,
VALOR_TOTAL FLOAT,
DATA_VENCIMENTO DATE,
ID_FORNECEDOR INT,
PRIMARY KEY (IDNF),
FOREIGN KEY (ID_FORNECEDOR) REFERENCES fornecedores (ID_FORNECEDOR));


CREATE TABLE itemnf
(ID_ITEM INT,
VALOR_ITEM FLOAT,
QUANTIDADE INT);

ALTER TABLE itemnf ADD PRIMARY KEY (ID_ITEM);

CREATE TABLE produto
(ID_PRODUTO INT,
DESCRICAO VARCHAR (200),
QUANTIDADE INT,
CUSTO FLOAT,
QUANTIDADE_MINIMA INT,
UNIDADE INT);

ALTER TABLE produto ADD PRIMARY KEY (ID_PRODUTO);

CREATE TABLE fornecedor
(ID_FORNECEDOR INT,
NOME VARCHAR (200),
RUA VARCHAR (50),
NUMERO INT,
BAIRRO VARCHAR (50),
CIDADE VARCHAR (50),
ESTADO VARCHAR (50),
CEP VARCHAR (8));

ALTER TABLE fornecedor ADD PRIMARY KEY (ID_FORNECEDOR);

INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (1,'2012-01-01',2000,'2012-01-10',4);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (2,'2012-01-01',1000,'2012-01-10',6);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (3,'2012-01-01',5500,'2012-01-10',3);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (4,'2012-01-10',1000,'2012-02-10',6);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (5,'2012-01-12',10000,'2012-02-10',1);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (6,'2012-02-05',10200,'2012-02-10',2);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (7,'2012-02-07',5000,'2012-02-10',3);
INSERT INTO  tbcabecalho (IDNF, DATA_EMISSAO, VALOR_TOTAL, DATA_VENCIMENTO, ID_FORNECEDOR)
VALUES (8,'2012-02-10',7500,'2012-03-10',5);


INSERT INTO fornecedor (ID_FORNECEDOR, NOME, CEP, ESTADO, CIDADE, BAIRRO, RUA, NUMERO)
VALUES ('1','Unnus',13874000,'SP','São João da Boa Vista','Rua Ademar de Barros',500);


INSERT INTO fornecedor (ID_FORNECEDOR, NOME, CEP, ESTADO, CIDADE, BAIRRO, RUA, NUMERO)